version: '3.8'

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "next-course"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
